{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ceeb6553",
   "metadata": {},
   "outputs": [],
   "source": [
    "### crazy navis import because if just import directly there is an error about fontconfig\n",
    "# https://github.com/navis-org/navis/issues/17\n",
    "import sys\n",
    "from unittest.mock import MagicMock\n",
    "\n",
    "# Mock vispy and relevant submodules\n",
    "sys.modules['vispy'] = MagicMock()\n",
    "sys.modules['vispy.util'] = MagicMock()\n",
    "sys.modules['vispy.gloo'] = MagicMock()\n",
    "sys.modules['vispy.gloo.util'] = MagicMock()\n",
    "sys.modules['vispy.util.transforms'] = MagicMock()\n",
    "sys.modules['vispy.util.quaternion'] = MagicMock()\n",
    "sys.modules['vispy.geometry'] = MagicMock()\n",
    "\n",
    "sys.modules['vispy.geometry'] = MagicMock()\n",
    "\n",
    "# Now you should be able to import navis\n",
    "import navis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8944926d",
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'fetch_skeletons' from 'neuprint' (/home/users/brezovec/.local/lib/python3.9/site-packages/neuprint/__init__.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_137661/1340261039.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mneuprint\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mfetch_neurons\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mneuprint\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mfetch_adjacencies\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mneuprint\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mfetch_skeletons\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m: cannot import name 'fetch_skeletons' from 'neuprint' (/home/users/brezovec/.local/lib/python3.9/site-packages/neuprint/__init__.py)"
     ]
    }
   ],
   "source": [
    "# from neuprint import Client\n",
    "# from neuprint import NeuronCriteria as NC\n",
    "# from neuprint import fetch_neurons\n",
    "# from neuprint import fetch_adjacencies\n",
    "# from neuprint import fetch_skeletons"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "50415e83",
   "metadata": {},
   "outputs": [],
   "source": [
    "#########################\n",
    "### connect to server ###\n",
    "#########################\n",
    "import navis.interfaces.neuprint as neu\n",
    "TOKEN = \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyZXpvdmVjQHN0YW5mb3JkLmVkdSIsImxldmVsIjoibm9hdXRoIiwiaW1hZ2UtdXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUl0YnZtbkRZbDlFVjYtZDhEZW5ueVUyZGNsVEtSQUYteGNXdHMtaWhQTjk9czk2LWM_c3o9NTA_c3o9NTAiLCJleHAiOjE4Mzg3ODI1NzF9.3LC0zWwmVC8RfbPZqrHz02MXk1RvbYP4ZIf6ygejh6E\" # <--- Paste your token here\n",
    "c = Client('neuprint.janelia.org', 'hemibrain:v1.2.1', TOKEN)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ad87a5ee",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Fetching:   0%|          | 0/58 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "pns = neu.fetch_skeletons(neu.NeuronCriteria(type='.*lPN.*', regex=True), with_synapses=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "ffb1bcd6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Dividing:   0%|          | 0/58 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Dotprops:   0%|          | 0/58 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Generate dotprops and convert to microns.\n",
    "pns_um = pns / (1000 / 8)\n",
    "pns_dps = navis.make_dotprops(pns_um, k=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "8833edd8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING : `OMP_NUM_THREADS` environment variable not set to \"1\". This may cause multiple layers of concurrency which in turn willslow down NBLAST when using multiple cores. See also https://github.com/navis-org/navis/issues/49 (navis)\n",
      "Process SpawnProcess-3:\n",
      "Traceback (most recent call last):\n",
      "  File \"/share/software/user/open/python/3.9.0/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/share/software/user/open/python/3.9.0/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/share/software/user/open/python/3.9.0/lib/python3.9/concurrent/futures/process.py\", line 237, in _process_worker\n",
      "    call_item = call_queue.get(block=True)\n",
      "  File \"/share/software/user/open/python/3.9.0/lib/python3.9/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/navis/__init__.py\", line 26, in <module>\n",
      "    from .plotting import *\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/navis/plotting/__init__.py\", line 15, in <module>\n",
      "    from .dd import *\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/navis/plotting/dd.py\", line 37, in <module>\n",
      "    from .plot_utils import segments_to_coords, tn_pairs_to_coords\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/navis/plotting/plot_utils.py\", line 32, in <module>\n",
      "    from vispy.util.transforms import rotate\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/vispy/__init__.py\", line 27, in <module>\n",
      "    from .util import config, set_log_level, keys, sys_info  # noqa\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/vispy/util/__init__.py\", line 14, in <module>\n",
      "    from . import fonts       # noqa\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/vispy/util/fonts/__init__.py\", line 13, in <module>\n",
      "    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/vispy/util/fonts/_triage.py\", line 11, in <module>\n",
      "    from ._freetype import _load_glyph\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/vispy/util/fonts/_freetype.py\", line 16, in <module>\n",
      "    from ...ext.fontconfig import find_font\n",
      "  File \"/home/users/brezovec/.local/lib/python3.9/site-packages/vispy/ext/fontconfig.py\", line 12, in <module>\n",
      "    raise ImportError('fontconfig not found')\n",
      "ImportError: fontconfig not found\n"
     ]
    },
    {
     "ename": "BrokenProcessPool",
     "evalue": "A process in the process pool was terminated abruptly while the future was running or pending.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mBrokenProcessPool\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_137661/1132185383.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Run an all-by-all NBLAST and synNBLAST\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mpns_nbl\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnavis\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnblast_allbyall\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpns_dps\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprogress\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/.local/lib/python3.9/site-packages/navis/nbl/nblast_funcs.py\u001b[0m in \u001b[0;36mnblast_allbyall\u001b[0;34m(x, normalized, use_alpha, smat, limit_dist, approx_nn, precision, n_cores, progress, smat_kwargs)\u001b[0m\n\u001b[1;32m   1110\u001b[0m                                  \u001b[0mdisable\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mnot\u001b[0m \u001b[0mprogress\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1111\u001b[0m                                  leave=False):\n\u001b[0;32m-> 1112\u001b[0;31m                 \u001b[0mres\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1113\u001b[0m                 \u001b[0mthis\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfutures\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1114\u001b[0m                 \u001b[0;31m# Fill-in big score matrix\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/share/software/user/open/python/3.9.0/lib/python3.9/concurrent/futures/_base.py\u001b[0m in \u001b[0;36mresult\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    431\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mCancelledError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    432\u001b[0m             \u001b[0;32melif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_state\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mFINISHED\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 433\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__get_result\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    434\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    435\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_condition\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/share/software/user/open/python/3.9.0/lib/python3.9/concurrent/futures/_base.py\u001b[0m in \u001b[0;36m__get_result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    387\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__get_result\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    388\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 389\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    390\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    391\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_result\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mBrokenProcessPool\u001b[0m: A process in the process pool was terminated abruptly while the future was running or pending."
     ]
    }
   ],
   "source": [
    "# Run an all-by-all NBLAST and synNBLAST\n",
    "pns_nbl = navis.nblast_allbyall(pns_dps, progress=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b1f83de1",
   "metadata": {},
   "outputs": [],
   "source": [
    "pns_nbl"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
